<?xml version="1.0" ?>

<!DOCTYPE articolo[

   <!ELEMENT articolo (paragrafo+)>
   <!ELEMENT paragrafo (immagine*, testo+, codice*)>

   <!ELEMENT immagine EMPTY>
   <!ELEMENT testo (#PCDATA)>
   <!ELEMENT codice (#PCDATA)>

   <!ATTLIST articolo titolo CDATA #REQUIRED>
   <!ATTLIST paragrafo 
         titolo   CDATA #IMPLIED
         tipo     (abstract|bibliografia|note) #IMPLIED
   >
   <!ATTLIST immagine file CDATA #REQUIRED> 
]>

<articolo titolo="Titolo dell'articolo">
   <paragrafo titolo="Titolo del primo paragrafo">
      <testo>
         Blocco di testo del primo paragrafo
      </testo>
      <immagine file="immagine1.jpg">
      </immagine>
   </paragrafo>
   <paragrafo titolo="Titolo del secondo paragrafo">
      <testo>
         Blocco di testo del secondo paragrafo
      </testo>
      <codice>
         Esempio di codice
      </codice>
      <testo>
         Altro blocco di testo
      </testo>
   </paragrafo>
   <paragrafo tipo="bibliografia">
      <testo>
         Riferimento ad un articolo
      </testo>
   </paragrafo>
</articolo>
